export const ROUTES = {
  landing: '/landing',
  customerHome: '/customer/home',
  customerAbout: '/about',
  customerMenu: '/menu',
  customerPromotions: '/promotions',
  customerBooking: '/booking',
  customerBlog: '/blog',
  customerStores: '/stores',
  customerMembership: '/membership',
  admin: '/admin',
  cms: '/cms',
  home: '/home',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
} as const
