export const ROUTES = {
  landing: '/landing',
  customerHome: '/landing',
  customerAbout: '/about',
  customerMenu: '/menu',
  customerPromotions: '/promotions',
  customerBooking: '/booking',
  customerBlog: '/blog',
  customerStores: '/stores',
  customerMembership: '/membership',
  adminDashboard: '/admin/dashboard',
  adminPos: '/admin/pos',
  adminOperations: '/admin/operations',
  adminInternal: '/admin/internal',
  adminOwner: '/admin/owner',
  adminCms: '/admin/cms',
  adminSettings: '/admin/settings',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
} as const
